# Generated by Django 4.0.5 on 2022-06-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aportador',
            fields=[
                ('idAportador', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id aportador')),
                ('nombreAportador', models.CharField(max_length=80, verbose_name='Nombre Aportador')),
                ('rutAportador', models.CharField(max_length=15, verbose_name='Rut Aportador')),
                ('usuarioAportador', models.CharField(max_length=30, verbose_name='Usuario Aportador')),
                ('passAportador', models.CharField(max_length=30, verbose_name='Pass Aportador')),
                ('correoAportador', models.CharField(max_length=30, verbose_name='Email Aportador')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('idAporte', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Aporte')),
                ('montoAporte', models.IntegerField(verbose_name='Monto de Aporte')),
                ('tarjetaAporte', models.IntegerField(max_length=16, verbose_name='Tarjeta de Aporte')),
                ('fechaAporte', models.DateField(verbose_name='Fecha del Aporte')),
                ('frecuenciaAporte', models.BooleanField(verbose_name='Frecuencia del aporte')),
                ('idAportador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.aportador')),
            ],
        ),
    ]
