# Generated by Django 4.0.5 on 2022-06-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportador',
            name='correoAportador',
            field=models.CharField(max_length=30, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='aportador',
            name='nombreAportador',
            field=models.CharField(max_length=80, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='aportador',
            name='passAportador',
            field=models.CharField(max_length=30, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='aportador',
            name='rutAportador',
            field=models.CharField(max_length=15, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='aportador',
            name='usuarioAportador',
            field=models.CharField(max_length=30, verbose_name='Nombre de Usuario'),
        ),
    ]
