# Generated by Django 4.0.5 on 2022-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aportador_correoaportador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='tarjetaAporte',
            field=models.CharField(max_length=16, verbose_name='Tarjeta de Aporte'),
        ),
    ]
