# Generated by Django 4.0.5 on 2022-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aporte_tarjetaaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='fechaAporte',
            field=models.CharField(max_length=30, verbose_name='Fecha del Aporte'),
        ),
    ]
