# Generated by Django 4.0.5 on 2022-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aporte_fechaaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='fechaAporte',
            field=models.DateTimeField(verbose_name='Fecha del Aporte'),
        ),
    ]
