# Generated by Django 4.0.5 on 2022-06-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aporte_fechaaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportador',
            name='apellidoAportador',
            field=models.CharField(default=None, max_length=80, verbose_name='Apellido Aportador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aportador',
            name='nombreAportador',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='fechaAporte',
            field=models.DateTimeField(verbose_name='Fecha del Aporte (Debe ser desde 2 días más en adelante) :'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='frecuenciaAporte',
            field=models.BooleanField(verbose_name='¿Aporte mensual?'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='idAportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.aportador', verbose_name='Nombre Aportador :'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='montoAporte',
            field=models.IntegerField(verbose_name='Monto de Aporte :'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='tarjetaAporte',
            field=models.CharField(max_length=16, verbose_name='Tarjeta de Aporte :'),
        ),
    ]
