# Generated by Django 4.0.5 on 2022-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aportador_apellidoaportador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='fechaAporte',
            field=models.DateField(verbose_name='Fecha del Aporte (Debe ser desde 2 días más en adelante) :'),
        ),
    ]
