# Generated by Django 4.0.5 on 2022-06-18 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='idAportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Aportador :'),
        ),
    ]
